# fly.toml app configuration file generated for app-restless-frost-6880 on 2024-10-30T17:04:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-restless-frost-6880'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
